name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    tags:
      description: 'Test scenario tags'
      required: false
      type: boolean
        
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.1.5

    env:
      CMD: ./src/paterl
      BIN: paterl/ebin
      INCLUDE: paterl/include
      SRC: paterl/src
      TEST: paterl/test

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          rm -rf $BIN/*.beam erl_crash.dump
          mkdir -p $BIN
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $SRC/*.erl $SRC/**/*.erl
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $TEST/**/*.erl
      - name: List
        run: |
          ls -lart $BIN
      - name: Test
        run: |
          echo "CodeBEAM/ID server test"
