name: Build

on: workflow_dispatch
        
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26.2.5

    env:
      CMD: /src/paterl
      BIN: ebin
      INCLUDE: include
      SRC: src
      TEST: test

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          rm -rf $BIN/*.beam erl_crash.dump
          mkdir -p $BIN
          pwd
          erlc -DTEST -pa ebin +debug_info -I include -o ebin src/*.erl src/**/*.erl
          # erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $TEST/**/*.erl
      - name: List
        run: |
          ls -lart $BIN
      - name: Test
        run: |
          echo "CodeBEAM/ID server test"
