name: Build

on: workflow_dispatch
        
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26.2.5

    env:
      CMD: src/paterl
      BIN: ebin
      INCLUDE: include
      SRC: src
      TEST: test

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          rm -rf $BIN/*.beam erl_crash.dump
          mkdir -p $BIN
          pwd
          erlc -DTEST +debug_info -W0 -I include -o $BIN $SRC/*.erl $SRC/**/*.erl
          erlc -DTEST -pa $BIN +debug_info -W0 -I $INCLUDE -o $BIN $TEST/*.erl
      - name: List
        run: |
          ls -lart $BIN
      - name: Test
        run: |
          echo "CodeBEAM/ID server test"
          $CMD $SRC/examples/erlang/codebeam/id_server_demo.erl -v all -I include -O $BIN
          diff $BIN/id_server_demo $TEST/generated/codebeam/id_ts_server_demo_ref
